require "matheus.options" -- `lua.` is implied
require "matheus.keymaps"
require "matheus.plugins"
require "matheus.nvimtree"
require "matheus.colorscheme"
require "matheus.cmp"
require "matheus.lsp"
require "matheus.treesitter"
require "matheus.colorizer"
--require "matheus.telescope"
--require "matheus.gitsigns"
--require "matheus.bufferline"
