require "matheus.options" -- `lua.` is implied
require "matheus.keymaps"
require "matheus.plugins"
require "matheus.cmp"
require "matheus.colorscheme"
require "matheus.lsp"
require "matheus.telescope"
require "matheus.treesitter"
require "matheus.gitsigns"
require "matheus.nvimtree"
